### ISSUE TITLE
Color Transition

### ISSUE THREAD

**Issue by kallyas** [diphan-source/colorDisplay#1]
That's some great work there @diphan-source 

I'm suggesting simple enhancement
on `<body>` element, add transition such that the colors fade in and out nicer
eg

```html
<body style="transition: all 2s cubic-bezier(0.25, 0.46, 0.45, 0.94) 1s">
<! -- some html here -->
</body>
```

Also the button
remove the outline with `outline: none` css property

**Comment by diphan-source** [comment]
thank you issue#1 resolved 
![body-transition](https://user-images.githubusercontent.com/62948017/132214781-21fc8ee0-4318-4162-a9e7-87309a91aba6.png)
![btn](https://user-images.githubusercontent.com/62948017/132214809-5851c2d3-a161-4021-8127-a5c3afc8914c.png)
